- name: Deploy MongoDB Cluster
  hosts: all
  become: true
  vars:
    replica_set_name: "rsdb"
    mongodb_port: 27017
    mongodb_data_dir: "/data/db"
    init_script: "$PWD/init-script.js"
  tasks:
    - name: Install MongoDB Dependency
      apt:
        name:
          - gnupg
        state: present

    - name: Add MongoDB repository key
      shell: "{wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -"

    - name: Add MongoDB repository file
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/{{ mongo_version }} multiverse
        state: present
        filename: "{{ mongo_repo_file }}"

    - name: Create MongoDB source.list
      file:
        path: "/etc/apt/sources.list.d/mongodb-org-5.0.list"
        state: file
        owner: root
        group: root

    - name: Add Repo Address to source.list
      shell: "echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB Package
      apt:
        name:
          - mongodb-org
        state: present

    - name: Hold auto update for MongoDB
      apt:
        name:
          - mongodb-org
          - mongodb-org-database
          - mongodb-org-server
          - mongodb-org-shell
          - mongodb-org-mongos
          - mongodb-org-tools
        state: held

    - name: Create MongoDB Data Directory
      file:
        path: "{{ mongodb_data_dir }}"
        state: directory
        owner: root
        group: root

    - name: Configure MongoDB
      template:
        src: mongodb.conf.j2
        dest: /etc/mongod.conf
      notify: restart mongod

    - name: Start MongoDB
      service:
        name: mongod
        state: started
        enabled: true

    - name: Wait for MongoDB to Start
      wait_for:
        port: "{{ mongodb_port }}"
        timeout: 30

    - name: Initialize MongoDB Replica Set
      shell: "mongo --eval 'rs.initiate()'"
      register: rs_init
      until: rs_init.rc == 0
      retries: 5
      delay: 5

    - name: Wait for Replica Set Initialization
      wait_for:
        port: "{{ mongodb_port }}"
        timeout: 30
        search_regex: "{{ replica_set_name }}.*PRIMARY"

    - name: Run MongoDB Cluster Initialization Script
      shell: "mongo --eval 'load(\"{{ init_script }}\")'"
      register: init_script_result
      ignore_errors: true

    - name: Verify MongoDB Cluster Initialization
      shell: "mongo --eval 'sh.status()' | grep 'active mongoses'"
      register: mongos_initialized
      retries: 5
      delay: 5
      until: mongos_initialized.rc == 0

  handlers:
    - name: Restart mongod
      service:
        name: mongod
        state: restarted