- name: Deploy MongoDB Cluster
  hosts: all
  become: true
  vars:
    replica_set_name: "rsdb"
    mongodb_port: 27017
    mongodb_data_dir: "/data/db"
  tasks:
    - name: Install MongoDB Dependency
      apt:
        name:
          - gnupg
        state: present

    - name: Add MongoDB repository key
      shell: "wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -"

    - name: Add MongoDB repository file
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
        state: present
        filename: "/etc/apt/sources.list.d/mongodb-org-5.0.list"

    - name: Install MongoDB Package
      apt:
        name:
          - mongodb-org
        state: present

    - name: Create MongoDB Data Directory
      file:
        path: "{{ mongodb_data_dir }}"
        state: directory
        owner: root
        group: root
    
    - name: Change Permission of Data Directory
      file:
        path: "{{ mongodb_data_dir }}"
        mode: 0777

    - name: Create MongoDB Log Directory
      file:
        path: "/var/log/mongodb"
        state: directory
        owner: root
        group: root

    - name: Change Permission of Log Directory
      file:
        path: "/var/log/mongodb"
        mode: 0777

    - name: Configure MongoDB
      template:
        src: mongodb.conf.j2
        dest: /etc/mongod.conf
      notify: Restart mongod

    - name: Start MongoDB
      service:
        name: mongod
        state: started
        enabled: true

    - name: Wait for MongoDB to Start
      wait_for:
        port: "{{ mongodb_port }}"
        timeout: 30

  handlers:
    - name: Restart mongod
      service:
        name: mongod
        state: restarted
---
- name: Initialize Mongo Cluster
  hosts: ini-node
  become: true
  vars:
    mongodb_port: 27017
    replica_set_name: "rsdb"

  tasks:

    - name: Copy Init MongoDB File
      template:
        src: init-script.js
        dest: /opt/init-script.js

    - name: Initiate MongoDB Cluster
      shell: "cat /opt/init-script.js | xargs mongo --eval "
    
    - name: Wait for MongoDB to Start
      wait_for:
        port: "{{ mongodb_port }}"
        timeout: 30

    - name: Wait for Replica Set Initialization
      wait_for:
        port: "{{ mongodb_port }}"
        timeout: 90
        search_regex: "{{ replica_set_name }}.*PRIMARY"

    - name: Verify MongoDB Cluster Initialization
      shell: "mongo --eval 'sh.status()' | grep 'active mongoses'"
      register: mongos_initialized
      retries: 5
      delay: 5
      until: mongos_initialized.rc == 0
